name: bwt_frontend
description: "BWT Frontend"

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  uuid: ^4.4.0
  intl: ^0.19.0
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  flutter_svg: ^2.0.10+1
  equatable: ^2.0.5
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.1
  loading_overlay: ^0.3.0
  flutter_screenutil: ^5.9.0
  smooth_page_indicator: ^1.1.0
  dropdown_search: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true