# Use a Node.js base image with a specific version
FROM node:14

# Set working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install application dependencies
RUN npm install

# Copy application source code to the working directory
COPY . .

# Run addToWallet.js to create identities
RUN node addToWallet.js

# Run submitDonation.js to perform initial setup action
RUN node submitDonation.js

# Expose port 3000 to the outside world
EXPOSE 3000

# Command to run the application gateway
CMD ["node", "app.js"]

# Add line

