name: Application Gateway Setup and Test

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches: [main]

jobs:
  setup-and-test-gateway:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: List workspace contents
        run: |
          echo "Listing workspace contents:"
          ls -R ${{ github.workspace }}

      - name: Check for fabric-samples
        run: |
          echo "Checking for fabric-samples:"
          find ${{ github.workspace }} -name fabric-samples

      - name: Set up Fabric
        run: |
          curl -sSL https://bit.ly/2ysbOFE | bash -s -- 2.2.0 1.4.9
          echo "${{ github.workspace }}/fabric-samples/bin" >> $GITHUB_PATH
          echo "FABRIC_CFG_PATH=${{ github.workspace }}/fabric-samples/config" >> $GITHUB_ENV

      - name: Check Fabric setup
        run: |
          echo "Checking Fabric setup:"
          ls -R ${{ github.workspace }}/fabric-samples

      - name: List fabric-samples directory
        run: |
          echo "Listing fabric-samples directory:"
          ls -R ${{ github.workspace }}/fabric-samples/test-network/organizations || true

      - name: Install dependencies
        working-directory: ./application-gateway
        run: npm install

      - name: Run addToWallet.js
        working-directory: ./application-gateway
        run: |
          echo "Current Directory: $(pwd)"
          node addToWallet.js

      # Add additional steps for testing the gateway if needed

      # - name: Test the gateway
      #   working-directory: ./application-gateway
      #   run: node submitDonation