
name: Application Gateway Setup and Test

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches: [main]

jobs:
  setup-and-test-gateway:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Set Fabric environment variables
        run: |
          echo "${{ github.workspace }}/fabric-samples/bin" >> $GITHUB_PATH
          echo "FABRIC_CFG_PATH=${{ github.workspace }}/fabric-samples/config" >> $GITHUB_ENV

      - name: Install dependencies
        working-directory: ./application-gateway
        run: npm install

      - name: Setting test network up
        working-directory: ./application-gateway
        run: |
          # Bring test network up
          cd ../fabric-samples/test-network
          ./network.sh up createChannel -ca -c mychannel -s couchdb

      - name: Run addToWallet.js
        working-directory: ./application-gateway
        run: |
          echo "Current Directory: $(pwd)" 
          node addToWallet.js

      # Add additional steps for testing the gateway if needed

      # - name: Test the gateway
      #   working-directory: ./application-gateway
      #   run: node submitDonation