name: Application Gateway Setup and Test

on:
  push:
    branches: [ main ]
    paths:
      - 'application-gateway/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'application-gateway/**'
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  setup-and-test-gateway:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        working-directory: ./application-gateway
        run: npm install

      - name: Run addToWallet.js
        working-directory: ./application-gateway
        run: node addToWallet.js

      # - name: Test the gateway
      #   working-directory: ./application-gateway
      #   run: node submitDonation
