name:  CI

on:
  push:
    branches: [ main ]
    paths:
      - 'chaincode/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'chaincode/**'

jobs:
  verify-chaincode:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      working-directory: ./chaincode
      run: npm install

    - name: Verify Node.js setup
      working-directory: ./chaincode
      run: node -e "console.log('Chaincode setup verified')"

    - name: Check for syntax errors
      working-directory: ./chaincode
      run: | 
        node --check lib/waterDonation.js
        npm run lint:json

    - name: Run unit tests
      working-directory: ./chaincode
      run: npm test

    - name: Run linter
      working-directory: ./chaincode
      run: npm run lint
    
    - name: Set up Fabric
      run: |
        curl -sSL https://bit.ly/2ysbOFE | bash -s -- 2.2.0 1.4.9
        export PATH=$PATH:$PWD/fabric-samples/bin
        export FABRIC_CFG_PATH=$PWD/fabric-samples/config

    - name: Run basic integration test
      working-directory: ./chaincode
      run: |
        # Create a test network
        cd ../fabric-samples/test-network
        ./network.sh up createChannel -ca -c mychannel -s couchdb

        #Add Org3 to test network
        cd ../test-network/addOrg3
        ./addOrg3.sh up

        # Back to test network
        cd ..
        
        # Deploy the chaincode
        ./network.sh deployCC -ccn water_donation -ccv 1.0 -ccp ../../chaincode -ccl javascript

        # Clean up
        # ./network.sh down