name: React Frontend CI

on:
  workflow_run:
    workflows: ["Web Application Backend CI"]
    types:
      - completed
    branches: [main]

jobs:
  # Builds and tests the React frontend application
  build-and-test:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      # Checks out the repository code 
      - name: Checkout repository
        uses: actions/checkout@v2

      # Sets up Node.js version 14 
      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Installs dependencies for the React frontend application
      - name: Install npm dependencies
        working-directory: ./react-frontend/aquatrustchain
        run: |
          npm install
          npm install --save-dev identity-obj-proxy

      # Runs unit tests for 
      - name: Run unit tests
        working-directory: ./react-frontend/aquatrustchain
        run: npm test -- --watchAll=false

      # Builds the production-ready bundle for the React frontend application
      - name: Build production bundle
        working-directory: ./react-frontend/aquatrustchain
        run: npm run build
