name: React Frontend CI

on:
  workflow_run:
    workflows: ["Web Application Backend CI"]
    types:
      - completed
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  

    - name: Install and update dependencies
      working-directory: ./react-frontend/aquatrustchain
      run: |
        npm install
        npm install --save-dev identity-obj-proxy
        npm install --save-dev @testing-library/react@latest
        npm install --save-dev react-scripts@latest

    - name: Run unit tests
      working-directory: ./react-frontend/aquatrustchain
      run: npm test -- --watchAll=false

    - name: Build
      working-directory: ./react-frontend/aquatrustchain
      run: npm run build